#ifndef THERMGLOBALS_H

#define THERMGLOBALS_H

#define LOG_ENABLED true

#define LORA_RFM9X_CS 10
#define LORA_RFM9X_INT 2
#define LORA_RFM9X_RST 4
#define LORA_RFM9X_FREQ 915.0

//#define LORA_RFM9X_MAX_MESSAGE_LEN 64
#define LORA_RFM9X_MAX_MESSAGE_LEN 128
#define LORA_MAX_CHUNK_SIZE 100 // leave 28 bytes for metadata
#define LORA_MAX_CHUNK_IN_BUFFER_SIZE 1024 // max size allowed for any chunk bunch
#define LORA_MAX_CHUNK_TIME_MILLIS 8000 // max time to wait for all chunks to arrive

#define LORA_CHUNK_START_KEY "CHUNKSTART"
#define LORA_CHUNK_END_KEY "CHUNKEND:"

#define LORA_ADDR_SELF 1
#define LORA_ADDR_REMOTE 0
#define LORA_ADDR_SPOTTER 1
#define LORA_ADDR_ACTOR 2
#define LORA_ADDR_BROADCAST 255

#define THERMAL_INTERPOLATE_BUFFER_SIZE 0
#define THERMAL_ENCODE_BUFFER_SIZE 768


#define THERMAL_WIDTH 32
#define THERMAL_HEIGHT 24

#endif